### ISSUE TITLE
How to remove "ctuthesis t1606152353"  which is at the bottom of every page?

### ISSUE THREAD

**Issue by TomHyhlik** [tohecz/ctuthesis#28]
Vedouci me bakalarske prace mi rekl, at odstranim vyse uvedeny napis, zjistil jsem, ze se nachazi ve trech souborech: ctuthesis.cls, ctuth-core.tex, ctuh-templates.tex.

Zkousel jsem o vsude zmenit, ale nemelo to vubec vliv. Jak ho tedy lze zmenit/odstrnit?

**Comment by tohecz** [comment]
Dobrý den,
někde v souboru máte pravděpodobně následující:

```
\ctusetup{
    preprint = \ctuverlog,
    ...
}
```

Mělo by stačit odstranit položku `preprint = \ctuverlog`. Prosím, dejte mi vědět, jestli to zafungovalo. Díky.

**Comment by TomHyhlik** [comment]
Funguje to, zmizelo to.Dekuji mockrat!
