### ISSUE TITLE
Vnější okraj / vnitřní okraj

### ISSUE THREAD

**Issue by trnkava1** [tohecz/ctuthesis#29]
Dobrý den, 

omlouvám se za možná trochu zbytečný dotaz, ale aktuálně píšu v šabloně diplomovou práci a všiml jsem si, že má šablona vnější okraj výrazně větší než vnitřní. Chtěl jsem se zeptat, jestli je to úmysl, nebo je chyba u mě? Zkoušel jsem si stránku vytisknout a na vnitřním okraji (u vazby) jsem naměřil něco přes 3 cm, u vnějšího okraje jsem naměřil přes 5 cm. Nemělo by to být spíše obráceně, aby byly okraje po svázání zhruba podobné?
 Porovnával jsem to s TEX šablonou (http://petr.olsak.net/ctustyle.html), kde je vnitřní i vnější okraj skoro stejný a raději bych se ujistil.

Děkuji za odpověď.

![okraje](https://cloud.githubusercontent.com/assets/17770036/25314330/320cf32a-2842-11e7-863f-d07e4cedab21.png)

**Comment by tohecz** [comment]
Dobrý den, je to úmysl, estetická záležitost, kdy v klasické typografii je snaha, aby při rozevřené knize byly všechny tři okraje (tedy vnější vlevo, oba vnitřní spolu, vnější vpravo) stejně veliké. Z vnitřního okraje při pevné vazbě něco odečítáme, ve výsledku by pak současné nastavení mělo fungovat. (Např. při kroužkové vazbě nebo brožurkovém šití sešívačkou se nic neodečítá a vnitřní okraj by pak mohl být ještě o chlup menší.)

**Comment by trnkava1** [comment]
Děkuji za vysvětlení a děkuji za šablonu. 👍
